name = "text-share-app"
compatibility_date = "2025-04-09"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

kv_namespaces = [
  { binding = "CLIPBOARD_KV", id = "57ff38517856492195cc72ece3219cf2" }
]

